# Generated by Django 4.2.13 on 2024-05-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BitcoinAddress",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=42, unique=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EthereumAddress",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=42, unique=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fii",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("negotiation_code", models.CharField(max_length=10, unique=True)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "updated_value",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("negotiation_code", models.CharField(max_length=10, unique=True)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "updated_value",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TreasuryDirect",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("product", models.CharField(max_length=10, unique=True)),
                ("indexer", models.CharField(max_length=50)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("deadline", models.DateTimeField()),
                (
                    "applied_value",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "brute_value",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "liquid_value",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "updated_value",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
