# Generated by Django 4.2.13 on 2024-05-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoinaddress',
            name='brl_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='ethereumaddress',
            name='brl_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
