# Generated by Django 4.2.13 on 2024-05-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finmanager', '0002_bitcoinaddress_brl_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurydirect',
            name='deadline',
            field=models.DateTimeField(blank=True),
        ),
    ]
