# Generated by Django 4.2.13 on 2024-05-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finmanager', '0004_remove_treasurydirect_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurydirect',
            name='deadline',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
